# Generated by Django 3.2.9 on 2022-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_table',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('usn', models.TextField(max_length=10, unique=True)),
                ('name', models.TextField(max_length=20)),
            ],
        ),
    ]
